package com.example.rentflat.enums;

public enum NotificationType {
    LISTING_APPROVED,
    LISTING_REJECTED,
    NEW_INQUIRY,
    INQUIRY_ACCEPTED,
    INQUIRY_REJECTED,
    NEW_MESSAGE,
    LEASE_SENT,
    LEASE_SIGNED,
    RENT_DUE,
    RENT_OVERDUE,
    SUBSCRIPTION_EXPIRING,
    SUBSCRIPTION_EXPIRED,
    KYC_APPROVED,
    KYC_REJECTED,
    SYSTEM,
    PROMOTION
}
